---
name: Egg-Model-FsaveDate
version: 0.01
author:
  - 'Masatoshi Mizuno E<lt>lusheE<64>cpan.orgE<gt>'
abstract: lib/Egg/Model/FsaveDate.pm
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Digest::SHA1: 2.11
  Egg::Release: 3.03
  File::Path: 2.04
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Egg::Helper::Model::FsaveDate:
    file: lib/Egg/Helper/Model/FsaveDate.pm
    version: 0.01
  Egg::Model::FsaveDate:
    file: lib/Egg/Model/FsaveDate.pm
    version: 0.01
  Egg::Model::FsaveDate::Base:
    file: lib/Egg/Model/FsaveDate/Base.pm
    version: 0.01
  Egg::Model::FsaveDate::handler:
    file: lib/Egg/Model/FsaveDate.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
